name: Deploy Bllog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-splx.site:
    - name: Deploy blog.splx.site
      uses: alinz/ssh-scp-action@master
      env:
        HELLO: cool
        MESSAGE: hello world
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        # runs this on remove server
        # rm -rf /var/www/blog.splx.site
        ssh_before: |
         cd /var/www/blog.splx.site && git pull
          echo $HELLO
          echo $MESSAGE
          ls -lath

        # then uploads these 2 files
        scp: |

        # then run these commands
        ssh_after: |
          echo $HELLO
          chmod -R 777 storage bootstrap/cache
          ls -lath
