name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
  deploy-splx.site:
    - name: SCP Upload
      # Вы можете прикрепить к точной фиксации или версии.
      # uses: betanzos/scp-upload@4afbc824f4b0940d2b1ae862590033424385e3ab
      uses: betanzos/scp-upload@v1
      with:
        # Source local file path
        source: /var/www/blog.splx.site
        # Remote host
        host: splx.site
        # Remote host SSH port
        port: # optional, default is 22
        # Remote host username
        username: splx
        # SSH private key
        key: 
        # Remote directory to copy the file
        remote_dir: # optional, default is ~
